spring:
    datasource:
          url: jdbc:mysql://localhost:3306/blog
          username: root
          password: 318210803qq
    mail:
          username: 1595704581@qq.com
          password: igehqmgmvyhqhcjc
          host: smtp.qq.com
          properties:
            mail:
              smtp:
                auth: true
                ssl:
                  enable: true
                starttls:
                  enable: true
                  required: true
          port: 465
    servlet:
          multipart:
            enabled: true
            max-file-size : 100MB
            max-request-size : 100MB